name: ✨ Feature Request
description: Suggest a new feature or enhancement for FORMA
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for helping improve FORMA!
        Please describe your feature request in detail below.

  - type: input
    id: title
    attributes:
      label: Feature Summary
      description: A clear and concise title for the feature
      placeholder: "e.g., Add exercise video demonstrations"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it clearly.
      placeholder: |
        A clear and concise description of what the problem is.
        Ex. "I'm always frustrated when..." or "It would be helpful if..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered.
        Why wouldn't these alternatives work as well?
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area of the app does this feature relate to?
      options:
        - UI/UX Improvement
        - New Exercise Feature
        - AI/Generation Enhancement
        - Performance Optimization
        - Admin Dashboard
        - PDF Export
        - Mobile Experience
        - Accessibility
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (Your Opinion)
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my experience
        - Important for my use case
        - Critical / Blocker
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, wireframes, or examples from other apps
      placeholder: "Drag and drop images here or paste links..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, references, or screenshots about the feature request
      placeholder: "Any additional information..."
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I have searched existing issues to ensure this feature hasn't already been requested
          required: true
        - label: I have read and agree to the project's Code of Conduct
          required: true
