-- =============================================================================
-- FORMA MIGRATION: Add Input Hash for Zero-Fund Caching
-- Description: Adds deterministic hash column for O(1) cache lookups
-- Run this in your Supabase SQL Editor
-- =============================================================================

-- Step 1: Add the input_hash column
ALTER TABLE public.generated_plans 
ADD COLUMN IF NOT EXISTS input_hash TEXT;

-- Step 2: Create unique constraint for cache integrity
ALTER TABLE public.generated_plans 
ADD CONSTRAINT unique_input_hash UNIQUE (input_hash);

-- Step 3: Create B-Tree index for O(1) lookups
CREATE INDEX IF NOT EXISTS idx_plans_input_hash 
ON public.generated_plans(input_hash);

-- Step 4: Add comment for documentation
COMMENT ON COLUMN public.generated_plans.input_hash IS 
'Deterministic SHA-256 hash of sorted user inputs for cache lookups. Generated by generateInputHash() in src/lib/hash.ts';

-- =============================================================================
-- VERIFICATION QUERY (Run after migration)
-- =============================================================================
-- SELECT column_name, data_type, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'generated_plans' AND column_name = 'input_hash';
